### ISSUE TITLE
TYPE_ACCELEROMETER - Doesn't stream any data on Android 13 + HIDL 2.0

### ISSUE THREAD

**Issue by jptcarreira** [STMicroelectronics/st-mems-android-linux-sensors-hal#7]
Hello, 
I installed the evaluation board STEVAL-MKI217V1 in a custom android board. After all configurations, I can read some sensors data from Android SENSOR_SERVICE, but not all that I'm looking for.

This is a list of some sensors that I read correctly:
TYPE_GYROSCOPE
TYPE_GYROSCOPE_UNCALIBRATED
TYPE_MAGNETIC_FIELD
TYPE_MAGNETIC_FIELD_UNCALIBRATED
(...)

My issue is with TYPE_ACCELEROMETER, I can read TYPE_ACCELEROMETER_UNCALIBRATED but *not* TYPE_ACCELEROMETER.

There are as well other sensor data that i'm interested in, but it just return zeros. The sensors are TYPE_ROTATION_VECTOR and TYPE_GAME_ROTATION_VECTOR. I suspect this is because the missing ACCELEROMETER data.

Any clue what I miss?

Log from logcat:

01-01 00:00:43.510  3435  3435 I stm-sensors: gyroscope rotation matrix: 1.000000,0.000000,0.000000;0.000000,1.000000,0.000000;0.000000,0.000000,1.000000
01-01 00:00:43.510  3435  3435 I stm-sensors: magnetometer rotation matrix: 1.000000,0.000000,0.000000;0.000000,1.000000,0.000000;0.000000,0.000000,1.000000
01-01 00:00:43.511  3435  3435 I stm-sensors: accelerometer rotation matrix: 1.000000,0.000000,0.000000;0.000000,1.000000,0.000000;0.000000,0.000000,1.000000
01-01 00:00:43.511  3435  3435 I stm-sensors: gyroscope placement: 0.000000, 0.000000, 0.000000
01-01 00:00:43.511  3435  3435 I stm-sensors: magnetometer placement: 0.000000, 0.000000, 0.000000
01-01 00:00:43.511  3435  3435 I stm-sensors: pressure placement: 0.000000, 0.000000, 0.000000
01-01 00:00:43.511  3435  3435 I stm-sensors: accelerometer placement: 10.000000, 20.000000, 30.000000
01-01 00:00:43.512  3435  3435 D stm-sensors: found 11 IIO devices available under /sys/bus/iio/devices
01-01 00:00:43.523  3435  3435 D stm-sensors: lsm6dsox_mlc: IIO device not supported by sensorHAL
01-01 00:00:43.524  3435  3435 E stm-sensors: lsm6dsox_sign_motion: failed to disable sensor.
01-01 00:00:43.530  3435  3435 D stm-sensors: lsm6dsox_temp: IIO device not supported by sensorHAL
01-01 00:00:43.542  3435  3435 D stm-sensors: lsm6dsox_mlc_0: IIO device not supported by sensorHAL
01-01 00:00:43.542  3435  3435 D stm-sensors: lsm6dsox_tilt: IIO device not supported by sensorHAL
01-01 00:00:43.542  3435  3435 D stm-sensors: meson-g12a-saradc: IIO device not supported by sensorHAL
01-01 00:00:43.543  3435  3435 E stm-sensors: lsm6dsox_step_d: failed to disable sensor.
01-01 00:00:43.543  3435  3435 D stm-sensors: LSM6DSOX Magnetometer Sensor: injection mode not available
01-01 00:00:43.543  3435  3435 I stm-sensors: magn calibration library: stm-magn-lib-mock
01-01 00:00:43.544  3435  3435 D stm-sensors: LSM6DSOX Accelerometer Sensor: injection mode not available
01-01 00:00:43.544  3435  3435 I stm-sensors: accel calibration library: stm-accel-lib-mock
01-01 00:00:43.545  3435  3435 D stm-sensors: LSM6DSOX Step Counter Sensor: injection mode not available
01-01 00:00:43.545  3435  3435 D stm-sensors: LSM6DSOX Gyroscope Sensor: injection mode not available
01-01 00:00:43.545  3435  3435 I stm-sensors: gyro calibration library: stm-gyro-lib-mock
01-01 00:00:43.546  3435  3435 I stm-sensors: sensors fusion (6X) library: stm-sensors-fusion-6X-lib-mock
01-01 00:00:43.546  3435  3435 I stm-sensors: sensors fusion (9X) library: stm-sensors-fusion-9X-lib-mock
01-01 00:00:43.567  3435  3435 E stm-sensors: selftest functions cannot be loaded correctly
01-01 00:00:43.567  3435  3435 D stm-sensors: 12 sensors available and ready
01-01 00:00:43.568  3435  3435 I stm-sensors: timesync library: stm-timesync-lib-mock
01-01 00:00:43.570  3435  3435 W stm-sensors: failed to load gyro bias
01-01 00:00:43.570  3435  3435 W stm-sensors: failed to load accel bias
01-01 00:00:43.570  3435  3435 E stm-sensors: failed to load magn bias
09-02 14:31:01.504  3435  3435 D stm-sensors: LSM6DSOX Accelerometer Sensor: changed pollrate to 5.000000Hz, timeout=1500ms
09-02 14:31:01.504  3435  3435 D stm-sensors: LSM6DSOX Accelerometer Sensor: power-on
09-02 14:31:02.192  3435  3785 W stm-sensors: cannot process 64bit channel
09-02 14:31:02.192  3435  3785 W stm-sensors: cannot process 64bit channel

Thanks,
João

**Comment by 20163100374** [comment]
@jptcarreira I encountered the same problem, have you solved it?

**Comment by jptcarreira** [comment]
> @jptcarreira I encountered the same problem, have you solved it?

Nope.... didn't find any solution, and I didn't receive any answer from ST. 
ST should care more about this HAL, and support the community.

**Comment by mariotesi** [comment]
Hi [jptcarreira](https://github.com/jptcarreira),

sorry for the late reply,

I'll start from the end, the sensors listed as iNemoEngine require a processing/fusion of the data coming from the hardware sensor base sensors (accel, gyro, temperature) and require the installation of proprietary libraries, this is the reason why you see zero output data from those virtual sensors. You can see for example here https://github.com/STMicroelectronics/st-mems-android-linux-sensors-hal/blob/ac20b4a1a8621b512c34e5b51cd822a142f7671f/core/libs/sensors-fusion/STMSensorsFusion.cpp#L20: 
this function are not implemented if sensor funsion library is not installed.

More or less the same goes for the calibration part, in that case accel, gyro and mag the calibration is managed by proprietary libraries that must be installed, if these are not installed the dynamic calibration of the basic sensor data is not performed and the offset will always be null.

As for the accelerometer sensor data, there is a full scale configuration issue in the driver, a patch (*) has been made to fix the problem and is being released on https://github.com/STMicroelectronics/st-mems-android-linux-drivers-iio, however I do not expect not to read data from the accelerometer, but rather to read data with an incorrect full scale. 

(*): basically the patch is in the st_lsm6dsox_set_full_scale function when comparing the full scale that SensorHAL sets based on the configuration files:
-               if (fs_table->fs_avl[i].gain == gain)
+               if (fs_table->fs_avl[i].gain >= gain)

**Comment by jptcarreira** [comment]
Thanks @mariotesi,

Where I request the  proprietary libraries?  Can you advise?

Thanks,

**Comment by mariotesi** [comment]
Hi jptcarreira,

The release of STM proprietary libraries is subject to signature of a License User Agreement (LUA); please contact an STMicroelectronics sales office and representatives for further information

**Comment by jptcarreira** [comment]
Thanks, I'll do that!
